# Generated by Django 4.2.1 on 2023-05-22 17:35

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='Nomi')),
                ('path', models.CharField(db_index=True, default='-', max_length=50)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.category', verbose_name='Otasi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Davlat',
                'verbose_name_plural': 'Davlatlar',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Til',
                'verbose_name_plural': 'Tillar',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to=main.models.image_rename)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to=main.models.file_rename)),
                ('like', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('dislike', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('read', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('added_at', models.DateTimeField(blank=True, default=datetime.datetime.now, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.datetime.now)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.language')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'index_together': {('title', 'added_at'), ('read', 'like', 'dislike')},
            },
        ),
    ]
