# Generated by Django 4.2.1 on 2023-05-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='added_at',
            new_name='date',
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together={('read', 'like', 'dislike'), ('title', 'date')},
        ),
    ]
