# Generated by Django 4.2.1 on 2023-05-25 16:31

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_added_at_post_date_alter_post_index_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_date',
            field=models.BooleanField(default=False, verbose_name='Muhim sana'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_library',
            field=models.BooleanField(default=False, verbose_name='Kutibxonaga tegishli'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_video_or_audio',
            field=models.BooleanField(default=False, verbose_name='Video yoki audio'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.category', verbose_name='Kategoriyasi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.country', verbose_name='Davlati'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.datetime.now)], verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=main.models.file_rename, verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.language', verbose_name='Tili'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=main.models.image_rename, verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='post',
            name='read',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="o'qildi"),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Sarlavha'),
        ),
    ]
