# Generated by Django 4.2.1 on 2023-05-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_post_is_library_remove_post_is_video_or_audio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='country',
        ),
        migrations.RemoveField(
            model_name='post',
            name='language',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
